config/routes.rb
Rails.application.routes.draw do
  resources :my_boices

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/my_boice.rb
class MyBoice < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_boices_controller.rb
class MyBoicesController < ApplicationController
  before_action :set_my_boice, only: [:show, :edit, :update, :destroy]

  # GET /my_boices
  # GET /my_boices.json
  def index
    @my_boices = MyBoice.all
  end

  # GET /my_boices/1
  # GET /my_boices/1.json
  def show
  end

  # GET /my_boices/new
  def new
    @my_boice = MyBoice.new
  end

  # GET /my_boices/1/edit
  def edit
  end

  # POST /my_boices
  # POST /my_boices.json
  def create
    @my_boice = MyBoice.new(my_boice_params)

    respond_to do |format|
      if @my_boice.save
        format.html { redirect_to @my_boice, notice: 'My boice was successfully created.' }
        format.json { render :show, status: :created, location: @my_boice }
      else
        format.html { render :new }
        format.json { render json: @my_boice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_boices/1
  # PATCH/PUT /my_boices/1.json
  def update
    respond_to do |format|
      if @my_boice.update(my_boice_params)
        format.html { redirect_to @my_boice, notice: 'My boice was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_boice }
      else
        format.html { render :edit }
        format.json { render json: @my_boice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_boices/1
  # DELETE /my_boices/1.json
  def destroy
    @my_boice.destroy
    respond_to do |format|
      format.html { redirect_to my_boices_url, notice: 'My boice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_boice
      @my_boice = MyBoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_boice_params
      params.require(:my_boice).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_boices_helper.rb
module MyBoicesHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/my_boices/_form.html.erb
<%= form_for @my_boice, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  my_boices_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/my_boices/edit.html.erb
<%- model_class = MyBoice -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => MyBoice %></h1>
</div>
<%= render :partial => 'form' %>

app/views/my_boices/index.html.erb
<%- model_class = MyBoice -%>
<div class="page-header">
  <h1><%=t '.title', :default => MyBoice %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @my_boices.each do |my_boice| %>
      <tr>
        <td><%= my_boice.id %></td>
        <td><%= my_boice.name %></td>
        <td><%= my_boice.description %></td>
        <td><%=l my_boice.created_at, format: :long %></td>
        <td>
          <%= link_to my_boice_path(my_boice), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to my_boice_path(my_boice), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_my_boice_path,
            :class => 'btn btn-primary' %>

app/views/my_boices/new.html.erb
<%- model_class = MyBoice -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => MyBoice %></h1>
</div>
<%= render :partial => 'form' %>

app/views/my_boices/show.html.erb
<%- model_class = MyBoice -%>
<div class="page-header">
  <h1><%=t '.title', :default => MyBoice %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @my_boice.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @my_boice.description %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              my_boices_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_my_boice_path(@my_boice), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              my_boice_path(@my_boice),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>